/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: Sample Project
 * Environment: Production
 * Project Id: 06614114-3fa0-0083-4ff8-363ed202ac05
 */
export const webhooks = {} as const;
