/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: Sample Project
 * Environment: Production
 * Project Id: 06614114-3fa0-0083-4ff8-363ed202ac05
 */
export const workflows = {
  /**
   * Default
   * Archived step Id: 7a535a69-ad34-47f8-806a-def1fdf4d391
   * Published step Id: b4363ccd-8f21-45fd-a840-5843d7b7f008
   */
  default: {
    codename: 'default',
    id: '00000000-0000-0000-0000-000000000000',
    name: 'Default',
  },
} as const;
